### ISSUE TITLE
Y U NO SUPPORT PHP5.6

### ISSUE THREAD

**Issue by ramondelafuente** [matthiasnoback/TalisORM#3]
![y-u-no-58072db93df78cbc28f27429](https://user-images.githubusercontent.com/668391/46558967-20ede280-c8ef-11e8-8d61-e086ef5b2026.png)

**Comment by ramondelafuente** [comment]
>>> https://github.com/ramondelafuente/TalisORM/commit/d1aa37303740781883aae304b5e77ee14044b0c6

**Comment by matthiasnoback** [comment]
Hehe I like this little GitHub issue storm man. Well, the plan was to make
it incompatible to have something to fight for. But I guess we could have a
5.6 compatible version hehe. Like a fork or something. Could be quite nice
and save us some code.

**Comment by ramondelafuente** [comment]
The fork is here: ramondelafuente@d1aa373 

I was just going to try and use the lib in my branch to "feel" it, but I'd need 5.6 support :P

**Comment by matthiasnoback** [comment]
That could work.
In that commit I also noticed that using the assertion was a mistake upon a
fix (I used an InvalidArgumentException before).

**Comment by matthiasnoback** [comment]
I decided to officially support 5.6. Since this would scratch our own itch
basically :) And I think more projects running on PHP 5.6 might benefit
from it. I'll probably add a one last feature that I think would be very
helpful (optimistic concurrency locking), and then I'll probably do another
round of feedback, after which version 1.0 should be ready to be used in
our project!

**Comment by ramondelafuente** [comment]
Nice. In my initial implementation (in our project) I used my "regular" repository, but gave it an AggregateRepository internally and that worked really well. So it's also a very neat way to migrate away from DoctrineORM by returning the doctrine models "fromState()" whithout breaking the doctrine repositories. So temporary side-by-side would work.

**Comment by ramondelafuente** [comment]
Supporting 5.6 hurts no-one at all, the only thing I removed where return types and scalar type-hints. Obviously the annotations should still point to the correct data types, so upgrading should be painless.

**Comment by matthiasnoback** [comment]
Very cool! Yes, this should be recommended usage for this library (I should write some more docs soon :)). And indeed, making it work with 5.6 is not hurtful. However, if people want to use Doctrine Migrations, they will need PHP 7. I'll add a comment to the README about it, now that I'm thinking of it hehe.

**Comment by matthiasnoback** [comment]
Closing this issue now, since it's fixed anyway!
