### ISSUE TITLE
Use EXISTS instead of COUNT operator

### ISSUE THREAD

**Issue by ahocquard** [matthiasnoback/TalisORM#4]
Hello,

https://github.com/matthiasnoback/TalisORM/blob/master/src/TalisOrm/AggregateRepository.php#L120

It is better to use EXISTS operator as it is more declarative for SQL to explain what you really want to do (declarative language).

Note:
When searching on a primary key like in this class, there is no difference between `count` and `exists`  in term of performance. So, it's not a big problem here.

When searching on a non-unique column, most of the SGBD stop the execution as soon as there is a tuple with `EXISTS` operator. This optimisation is possible because you ask what you want. That's not the case with a count.

**Comment by matthiasnoback** [comment]
Thanks for this excellent suggestion! I'll work on it.

**Comment by matthiasnoback** [comment]
Since this functionality is intended to be used only for primary keys, I think it will keep the code simpler if I don't rewrite it to use `EXISTS`. Thanks for your suggestion though, and if performance pops up in user-submitted issues, I'll definitely keep this one in mind!
